-- Criação do banco de dados 'industria'
CREATE DATABASE industria;

-- As instruções para criar as tabelas devem ser executadas após se conectar ao banco de dados 'industria'

-- Tabela de peças
CREATE TABLE pecas (
    pec_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pec_numero INT,
    pec_cor VARCHAR(50),
    pec_valor INT,
    pec_peso FLOAT
);

-- Tabela de depósitos
CREATE TABLE deposito (
    dep_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dep_numero INT,
    dep_endereco VARCHAR(255)
);

-- Tabela de fornecedores
CREATE TABLE fornecedor (
    for_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    for_numero INT,
    for_endereco VARCHAR(255),
    for_nome VARCHAR(255)
);

-- Tabela de projetos
CREATE TABLE projeto (
    pro_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pro_numero INT,
    pro_orcamento INT,
    pro_descricao VARCHAR(255)
);

-- Tabela de departamentos
CREATE TABLE departamento (
    dep_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dep_numero INT,
    dep_setor INT
);

-- Tabela de funcionários
CREATE TABLE funcionario (
    fun_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fun_numero INT,
    fun_salario INT,
    fun_telefone VARCHAR(12),
    fun_nome VARCHAR(100),
    dep_id INT,
    FOREIGN KEY (dep_id) REFERENCES departamento(dep_id)
);

-- Tabela associativa para funcionários e projetos
CREATE TABLE funcionario_projeto (
    fun_id INT,
    pro_id INT,
    data_inicio DATE,
    horas_trabalhadas INT,
    PRIMARY KEY (fun_id, pro_id),
    FOREIGN KEY (fun_id) REFERENCES funcionario(fun_id),
    FOREIGN KEY (pro_id) REFERENCES projeto(pro_id)
);

-- Tabela associativa para projetos e fornecedores
CREATE TABLE projeto_fornecedor (
    pro_id INT,
    for_id INT,
    PRIMARY KEY (pro_id, for_id),
    FOREIGN KEY (pro_id) REFERENCES projeto(pro_id),
    FOREIGN KEY (for_id) REFERENCES fornecedor(for_id)
);

-- Tabela associativa para projetos, peças e fornecedores
CREATE TABLE projeto_peca (
    pro_id INT,
    pec_id INT,
    for_id INT,
    PRIMARY KEY (pro_id, pec_id, for_id),
    FOREIGN KEY (pro_id) REFERENCES projeto(pro_id),
    FOREIGN KEY (pec_id) REFERENCES pecas(pec_id),
    FOREIGN KEY (for_id) REFERENCES fornecedor(for_id)
);

-- Tabela associativa para depósitos e peças
CREATE TABLE deposito_peca (
    dep_id INT,
    pec_id INT,
    quantidade INT,
    PRIMARY KEY (dep_id, pec_id),
    FOREIGN KEY (dep_id) REFERENCES deposito(dep_id),
    FOREIGN KEY (pec_id) REFERENCES pecas(pec_id)
);
